# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0

defaults: &defaults
  working_directory: ~/project/vue-router
  docker:
    - image: circleci/node:12


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-cache-{{ .Branch }}-
            - v1-dependencies-cache-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-router

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn build
      - run: yarn build:dts

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test:unit  --maxWorkers=2
      - store_artifacts:
          path: coverage


  lint-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn lint
      - run: yarn test:types

  coverage:
    <<: *defaults
      - run:
          name: Send code coverage
          command: yarn run codecov

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint-types:
          requires:
            - install
      - test-unit:
          requires:
            - install
      - coverage:
          requires:
            - build
            - test-unit
            - lint-types
